# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
    - master
    
jobs:
   gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    
    env:
      project-name: plus-util
      target-dir: /home/seeminglyjs/deploy/$project-name
      from-dir: ./
#       GIT_STRATEGY: clone
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
#     - uses: gradle/gradle-build-action@v2
#       with:
#         arguments: build
#        build-root-directory: /home/seeminglyjs/github/plus-util     
#         build-root-directory: /home/seeminglyjs/project/plus-util    
#         gradle-executable: /home/seeminglyjs/github/plus-util  
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-executable: /home/seeminglyjs/github/plus-util  
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Execute Gradle build
      run: ./gradlew build
      
    - name: Make Directory for deliver
      run: mkdir -p $target-dir
      
    - name: rsync delete
      run: rsync -avz --delete $from-dir $target-dir

    - name: after rsync
      run: cd .. && rm -rf $project-name/*

